export const Data = [
    {
        id: 1,
        method: 'Мозкова атака',
        identifying: 'Завжди застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },
    {
        id: 2,
        method: 'Структуроване чи напівструктуроване опитування',
        identifying: 'Завжди застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 3,
        method: 'Метод Дельфі',
        identifying: 'Завжди застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 4,
        method: 'Переліки контрольних запитань',
        identifying: 'Завжди застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 5,
        method: 'Попереднє аналізування небезпечних чинників',
        identifying: 'Завжди застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 6,
        method: 'Дослідження небезпечних чинників і працездатності',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 7,
        method: 'Аналізування небезпечних чинників і критичні точки контролю',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Завжди застосовний',
    },{
        id: 8,
        method: 'Загальне оцінювання екологічного ризику',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Завжди застосовний',
    },{
        id: 9,
        method: 'Структурований метод. "Що - якщо"',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Завжди застосовний',
    },{
        id: 10,
        method: 'Аналізування сценріїв',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 11,
        method: 'Аналізування впливу на діяльність',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 12,
        method: 'Аналізування першопричини',
        identifying: 'Незастосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Завжди застосовний',
    },{
        id: 13,
        method: 'Аналізування видів і наслідків відмов',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Завжди застосовний',
    },{
        id: 14,
        method: 'Аналізування дерева відмов',
        identifying: 'Застосовний',
        consequence: 'Незастосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 15,
        method: 'Аналізування дерева подій',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 16,
        method: 'Аналізування причин і наслідків',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 17,
        method: 'Аналізування причинно-наслідкових зв\'язків',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 18,
        method: 'Аналізування рівнів захисту',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 19,
        method: 'Дерево рішень',
        identifying: 'Незастосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 20,
        method: 'Загальне оцінювання ндійності людини',
        identifying: 'Завжди застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },{
        id: 21,
        method: 'Аналізування за схемою "краватка-метелик"',
        identifying: 'Незастосовний',
        consequence: 'Застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Застосовний',
    },{
        id: 22,
        method: 'Технічне обслуговування, зорієнтоване на забезпечення безвідмовності',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Завжди застосовний',
    },
    {
        id: 23,
        method: 'Аналізування паразитних схем',
        identifying: 'Застосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },
    {
        id: 24,
        method: 'Марковське аналізування',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Незастосовний',
    },
    {
        id: 25,
        method: 'Імітаційне моделювання за методом Монте-Карло',
        identifying: 'Незастосовний',
        consequence: 'Незастосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Завжди застосовний',
    },
    {
        id: 26,
        method: 'Байєсова статистика і мережі Байєеса',
        identifying: 'Незастосовний',
        consequence: 'Завжди застосовний',
        probability: 'Незастосовний',
        riskLevel: 'Незастосовний',
        riskValuation: 'Завжди застосовний',
    },
    {
        id: 27,
        method: 'Криві FN',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Завжди застосовний',
    },
    {
        id: 28,
        method: 'Показники ризику',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Завжди застосовний',
    },{
        id: 29,
        method: 'Матриця "наслідок-ймовірність"',
        identifying: 'Завжди застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Завжди застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Застосовний',
    },
    {
        id: 30,
        method: 'Аналізування витрат і вигод',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Застосовний',
        riskValuation: 'Застосовний',
    },
    {
        id: 31,
        method: 'Багатокритерійне аналізування рішень',
        identifying: 'Застосовний',
        consequence: 'Завжди застосовний',
        probability: 'Застосовний',
        riskLevel: 'Завжди застосовний',
        riskValuation: 'Застосовний',
    }
]